### ISSUE TITLE
Add proper image support

### ISSUE THREAD

**Issue by samwightt** [samwightt/chorale#1]
While images work right now, they don't render properly. Things that need to be done:

- [x] Images need to be centered.
- [x] Images need to be resized according to the size given from the Notion API.
- [x] Images need to be lazily loaded
- [x] Images need to have alt content and captions added.
- [ ] Page cover images need to be supported.
- [x] Images need a placeholder while lazily loading.

**Comment by michello** [comment]
@samwightt Hiya! Would love to help out if you don't mind. :)

**Comment by samwightt** [comment]
Sure, that's totally fine! It's been a minute since I touched this repo, but my work (as far as I can remember) on lazy loading images was in the `feat/add-lazyload-image` branch (see #10). Feel free to look at that and add any other stuff you want!

**Comment by samwightt** [comment]
Hey @michello is there any update on this?
